const CurrenciesCode = [
    { code: 'USD', label: 'US Dollar', symbol: '$', chart: true },
    { code: 'AED', label: 'UAE Dirham', symbol: 'د.إ', chart: false },
    { code: 'AFN', label: 'Afghan Afghani', symbol: '؋', chart: false },
    { code: 'ALL', label: 'Albanian Lek', symbol: 'L', chart: false },
    { code: 'AMD', label: 'Armenian Dram', symbol: '֏', chart: false },
    { code: 'ANG', label: 'Netherlands Antillean Guilder', symbol: 'ƒ', chart: false },
    { code: 'AOA', label: 'Angolan Kwanza', symbol: 'Kz', chart: false },
    { code: 'ARS', label: 'Argentine Peso', symbol: '$', chart: false },
    { code: 'AUD', label: 'Australian Dollar', symbol: '$', chart: true },
    { code: 'AWG', label: 'Aruban Florin', symbol: 'ƒ', chart: false },
    { code: 'AZN', label: 'Azerbaijani Manat', symbol: '₼', chart: false },
    { code: 'BAM', label: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', chart: false },
    { code: 'BBD', label: 'Barbadian Dollar', symbol: '$', chart: false },
    { code: 'BDT', label: 'Bangladeshi Taka', symbol: '৳', chart: false },
    { code: 'BGN', label: 'Bulgarian Lev', symbol: 'лв', chart: true },
    { code: 'BHD', label: 'Bahraini Dinar', symbol: 'ب.د', chart: false },
    { code: 'BIF', label: 'Burundian Franc', symbol: 'FBu', chart: false },
    { code: 'BMD', label: 'Bermudian Dollar', symbol: '$', chart: false },
    { code: 'BND', label: 'Brunei Dollar', symbol: '$', chart: false },
    { code: 'BOB', label: 'Bolivian Boliviano', symbol: 'Bs.', chart: false },
    { code: 'BRL', label: 'Brazilian Real', symbol: 'R$', chart: true },
    { code: 'BSD', label: 'Bahamian Dollar', symbol: '$', chart: false },
    { code: 'BTN', label: 'Bhutanese Ngultrum', symbol: 'Nu.', chart: false },
    { code: 'BWP', label: 'Botswanan Pula', symbol: 'P', chart: false },
    { code: 'BYN', label: 'Belarusian Ruble', symbol: 'Br', chart: false },
    { code: 'BZD', label: 'Belize Dollar', symbol: '$', chart: false },
    { code: 'CAD', label: 'Canadian Dollar', symbol: '$', chart: true },
    { code: 'CDF', label: 'Congolese Franc', symbol: 'FC', chart: false },
    { code: 'CHF', label: 'Swiss Franc', symbol: 'CHF', chart: true },
    { code: 'CLP', label: 'Chilean Peso', symbol: '$', chart: false },
    { code: 'CNY', label: 'Chinese Yuan', symbol: '¥', chart: true },
    { code: 'COP', label: 'Colombian Peso', symbol: '$', chart: false },
    { code: 'CRC', label: 'Costa Rican Colón', symbol: '₡', chart: false },
    { code: 'CUP', label: 'Cuban Peso', symbol: '$', chart: false },
    { code: 'CVE', label: 'Cape Verdean Escudo', symbol: 'Esc', chart: false },
    { code: 'CZK', label: 'Czech Koruna', symbol: 'Kč', chart: true },
    { code: 'DJF', label: 'Djiboutian Franc', symbol: 'Fdj', chart: false },
    { code: 'DKK', label: 'Danish Krone', symbol: 'kr', chart: true },
    { code: 'DOP', label: 'Dominican Peso', symbol: '$', chart: false },
    { code: 'DZD', label: 'Algerian Dinar', symbol: 'د.ج', chart: false },
    { code: 'EGP', label: 'Egyptian Pound', symbol: '£', chart: false },
    { code: 'ERN', label: 'Eritrean Nakfa', symbol: 'Nkf', chart: false },
    { code: 'ETB', label: 'Ethiopian Birr', symbol: 'Br', chart: false },
    { code: 'EUR', label: 'Euro', symbol: '€', chart: true },
    { code: 'FJD', label: 'Fijian Dollar', symbol: '$', chart: false },
    { code: 'FKP', label: 'Falkland Islands Pound', symbol: '£', chart: false },
    { code: 'FOK', label: 'Faroese Króna', symbol: 'kr', chart: false },
    { code: 'GBP', label: 'British Pound Sterling', symbol: '£', chart: true },
    { code: 'GEL', label: 'Georgian Lari', symbol: '₾', chart: false },
    { code: 'GGP', label: 'Guernsey Pound', symbol: '£', chart: false },
    { code: 'GHS', label: 'Ghanaian Cedi', symbol: '₵', chart: false },
    { code: 'GIP', label: 'Gibraltar Pound', symbol: '£', chart: false },
    { code: 'GMD', label: 'Gambian Dalasi', symbol: 'D', chart: false },
    { code: 'GNF', label: 'Guinean Franc', symbol: 'FG', chart: false },
    { code: 'GTQ', label: 'Guatemalan Quetzal', symbol: 'Q', chart: false },
    { code: 'GYD', label: 'Guyanese Dollar', symbol: '$', chart: false },
    { code: 'HKD', label: 'Hong Kong Dollar', symbol: '$', chart: true },
    { code: 'HNL', label: 'Honduran Lempira', symbol: 'L', chart: false },
    { code: 'HRK', label: 'Croatian Kuna', symbol: 'kn', chart: false },
    { code: 'HTG', label: 'Haitian Gourde', symbol: 'G', chart: false },
    { code: 'HUF', label: 'Hungarian Forint', symbol: 'Ft', chart: true },
    { code: 'IDR', label: 'Indonesian Rupiah', symbol: 'Rp', chart: true },
    { code: 'ILS', label: 'Israeli Shekel', symbol: '₪', chart: true },
    { code: 'IMP', label: 'Isle of Man Pound', symbol: '£', chart: false },
    { code: 'INR', label: 'Indian Rupee', symbol: '₹', chart: true },
    { code: 'IQD', label: 'Iraqi Dinar', symbol: 'ع.د', chart: false },
    { code: 'IRR', label: 'Iranian Rial', symbol: '﷼', chart: false },
    { code: 'ISK', label: 'Icelandic Króna', symbol: 'kr', chart: true },
    { code: 'JEP', label: 'Jersey Pound', symbol: '£', chart: false },
    { code: 'JMD', label: 'Jamaican Dollar', symbol: '$', chart: false },
    { code: 'JOD', label: 'Jordanian Dinar', symbol: 'د.ا', chart: false },
    { code: 'JPY', label: 'Japanese Yen', symbol: '¥', chart: true },
    { code: 'KES', label: 'Kenyan Shilling', symbol: 'KSh', chart: false },
    { code: 'KGS', label: 'Kyrgystani Som', symbol: 'с', chart: false },
    { code: 'KHR', label: 'Cambodian Riel', symbol: '៛', chart: false },
    { code: 'KID', label: 'Kiribati Dollar', symbol: '$', chart: false },
    { code: 'KMF', label: 'Comorian Franc', symbol: 'CF', chart: false },
    { code: 'KRW', label: 'South Korean Won', symbol: '₩', chart: true },
    { code: 'KWD', label: 'Kuwaiti Dinar', symbol: 'د.ك', chart: false },
    { code: 'KYD', label: 'Cayman Islands Dollar', symbol: '$', chart: false },
    { code: 'KZT', label: 'Kazakhstani Tenge', symbol: '₸', chart: false },
    { code: 'LAK', label: 'Laotian Kip', symbol: '₭', chart: false },
    { code: 'LBP', label: 'Lebanese Pound', symbol: 'ل.ل', chart: false },
    { code: 'LKR', label: 'Sri Lankan Rupee', symbol: 'Rs', chart: false },
    { code: 'LRD', label: 'Liberian Dollar', symbol: '$', chart: false },
    { code: 'LSL', label: 'Lesotho Loti', symbol: 'L', chart: false },
    { code: 'LYD', label: 'Libyan Dinar', symbol: 'ل.د', chart: false },
    { code: 'MAD', label: 'Moroccan Dirham', symbol: 'د.م.', chart: false },
    { code: 'MDL', label: 'Moldovan Leu', symbol: 'L', chart: false },
    { code: 'MGA', label: 'Malagasy Ariary', symbol: 'Ar', chart: false },
    { code: 'MKD', label: 'Macedonian Denar', symbol: 'ден', chart: false },
    { code: 'MMK', label: 'Myanmar Kyat', symbol: 'Ks', chart: false },
    { code: 'MNT', label: 'Mongolian Tugrik', symbol: '₮', chart: false },
    { code: 'MOP', label: 'Macanese Pataca', symbol: 'MOP$', chart: false },
    { code: 'MRU', label: 'Mauritanian Ouguiya', symbol: 'UM', chart: false },
    { code: 'MUR', label: 'Mauritian Rupee', symbol: '₨', chart: false },
    { code: 'MVR', label: 'Maldivian Rufiyaa', symbol: 'Rf', chart: false },
    { code: 'MWK', label: 'Malawian Kwacha', symbol: 'MK', chart: false },
    { code: 'MXN', label: 'Mexican Peso', symbol: '$', chart: true },
    { code: 'MYR', label: 'Malaysian Ringgit', symbol: 'RM', chart: true },
    { code: 'MZN', label: 'Mozambican Metical', symbol: 'MT', chart: false },
    { code: 'NAD', label: 'Namibian Dollar', symbol: '$', chart: false },
    { code: 'NGN', label: 'Nigerian Naira', symbol: '₦', chart: false },
    { code: 'NIO', label: 'Nicaraguan Córdoba', symbol: 'C$', chart: false },
    { code: 'NOK', label: 'Norwegian Krone', symbol: 'kr', chart: true },
    { code: 'NPR', label: 'Nepalese Rupee', symbol: '₨', chart: false },
    { code: 'NZD', label: 'New Zealand Dollar', symbol: '$', chart: true },
    { code: 'OMR', label: 'Omani Rial', symbol: 'ر.ع.', chart: false },
    { code: 'PAB', label: 'Panamanian Balboa', symbol: 'B/.', chart: false },
    { code: 'PEN', label: 'Peruvian Sol', symbol: 'S/', chart: false },
    { code: 'PGK', label: 'Papua New Guinean Kina', symbol: 'K', chart: false },
    { code: 'PHP', label: 'Philippine Peso', symbol: '₱', chart: true },
    { code: 'PKR', label: 'Pakistani Rupee', symbol: '₨', chart: false },
    { code: 'PLN', label: 'Polish Złoty', symbol: 'zł', chart: true },
    { code: 'PYG', label: 'Paraguayan Guarani', symbol: '₲', chart: false },
    { code: 'QAR', label: 'Qatari Rial', symbol: 'ر.ق', chart: false },
    { code: 'RON', label: 'Romanian Leu', symbol: 'lei', chart: true },
    { code: 'RSD', label: 'Serbian Dinar', symbol: 'дин', chart: false },
    { code: 'RUB', label: 'Russian Ruble', symbol: '₽', chart: false },
    { code: 'RWF', label: 'Rwandan Franc', symbol: 'FRw', chart: false },
    { code: 'SAR', label: 'Saudi Riyal', symbol: 'ر.س', chart: false },
    { code: 'SBD', label: 'Solomon Islands Dollar', symbol: '$', chart: false },
    { code: 'SCR', label: 'Seychellois Rupee', symbol: '₨', chart: false },
    { code: 'SDG', label: 'Sudanese Pound', symbol: '£', chart: false },
    { code: 'SEK', label: 'Swedish Krona', symbol: 'kr', chart: true },
    { code: 'SGD', label: 'Singapore Dollar', symbol: '$', chart: true },
    { code: 'SHP', label: 'St Helena Pound', symbol: '£', chart: false },
    { code: 'SLE', label: 'Sierra Leonean Leone', symbol: 'Le', chart: false },
    { code: 'SLL', label: 'Sierra Leonean Leone (old)', symbol: 'Le', chart: false },
    { code: 'SOS', label: 'Somali Shilling', symbol: 'Sh', chart: false },
    { code: 'SRD', label: 'Surinamese Dollar', symbol: '$', chart: false },
    { code: 'SSP', label: 'South Sudanese Pound', symbol: '£', chart: false },
    { code: 'STN', label: 'São Tomé & Príncipe Dobra', symbol: 'Db', chart: false },
    { code: 'SYP', label: 'Syrian Pound', symbol: '£', chart: false },
    { code: 'SZL', label: 'Swazi Lilangeni', symbol: 'E', chart: false },
    { code: 'THB', label: 'Thai Baht', symbol: '฿', chart: true },
    { code: 'TJS', label: 'Tajikistani Somoni', symbol: 'SM', chart: false },
    { code: 'TMT', label: 'Turkmenistani Manat', symbol: 'T', chart: false },
    { code: 'TND', label: 'Tunisian Dinar', symbol: 'د.ت', chart: false },
    { code: 'TOP', label: 'Tongan Paʻanga', symbol: 'T$', chart: false },
    { code: 'TRY', label: 'Turkish Lira', symbol: '₺', chart: true },
    { code: 'TTD', label: 'Trinidad & Tobago Dollar', symbol: '$', chart: false },
    { code: 'TVD', label: 'Tuvaluan Dollar', symbol: '$', chart: false },
    { code: 'TWD', label: 'New Taiwan Dollar', symbol: 'NT$', chart: false },
    { code: 'TZS', label: 'Tanzanian Shilling', symbol: 'Sh', chart: false },
    { code: 'UAH', label: 'Ukrainian Hryvnia', symbol: '₴', chart: false },
    { code: 'UGX', label: 'Ugandan Shilling', symbol: 'Sh', chart: false },
    { code: 'UYU', label: 'Uruguayan Peso', symbol: '$', chart: false },
    { code: 'UZS', label: 'Uzbekistani Som', symbol: 'soʻm', chart: false },
    { code: 'VES', label: 'Venezuelan Bolívar', symbol: 'Bs.', chart: false },
    { code: 'VND', label: 'Vietnamese Đồng', symbol: '₫', chart: false },
    { code: 'VUV', label: 'Vanuatu Vatu', symbol: 'Vt', chart: false },
    { code: 'WST', label: 'Samoan Tala', symbol: 'T', chart: false },
    { code: 'XAF', label: 'Central African CFA Franc', symbol: 'FCFA', chart: false },
    { code: 'XCD', label: 'East Caribbean Dollar', symbol: '$', chart: false },
    { code: 'XDR', label: 'IMF Special Drawing Rights', symbol: 'SDR', chart: false },
    { code: 'XOF', label: 'West African CFA Franc', symbol: 'CFA', chart: false },
    { code: 'XPF', label: 'CFP Franc', symbol: '₣', chart: false },
    { code: 'YER', label: 'Yemeni Rial', symbol: '﷼', chart: false },
    { code: 'ZAR', label: 'South African Rand', symbol: 'R', chart: true },
    { code: 'ZMW', label: 'Zambian Kwacha', symbol: 'ZK', chart: false },
    { code: 'ZWL', label: 'Zimbabwean Dollar', symbol: '$', chart: false }
];

export default CurrenciesCode;