const CurrenciesCode = [
    { code: 'USD', label: 'US Dollar', symbol: '$', flag: '🇺🇸' },
    { code: 'AED', label: 'UAE Dirham', symbol: 'د.إ', flag: '🇦🇪' },
    { code: 'AFN', label: 'Afghan Afghani', symbol: '؋', flag: '🇦🇫' },
    { code: 'ALL', label: 'Albanian Lek', symbol: 'L', flag: '🇦🇱' },
    { code: 'AMD', label: 'Armenian Dram', symbol: '֏', flag: '🇦🇲' },
    { code: 'ANG', label: 'Netherlands Antillean Guilder', symbol: 'ƒ', flag: '🇨🇼' },
    { code: 'AOA', label: 'Angolan Kwanza', symbol: 'Kz', flag: '🇦🇴' },
    { code: 'ARS', label: 'Argentine Peso', symbol: '$', flag: '🇦🇷' },
    { code: 'AUD', label: 'Australian Dollar', symbol: '$', flag: '🇦🇺' },
    { code: 'AWG', label: 'Aruban Florin', symbol: 'ƒ', flag: '🇦🇼' },
    { code: 'AZN', label: 'Azerbaijani Manat', symbol: '₼', flag: '🇦🇿' },
    { code: 'BAM', label: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', flag: '🇧🇦' },
    { code: 'BBD', label: 'Barbadian Dollar', symbol: '$', flag: '🇧🇧' },
    { code: 'BDT', label: 'Bangladeshi Taka', symbol: '৳', flag: '🇧🇩' },
    { code: 'BGN', label: 'Bulgarian Lev', symbol: 'лв', flag: '🇧🇬' },
    { code: 'BHD', label: 'Bahraini Dinar', symbol: 'ب.د', flag: '🇧🇭' },
    { code: 'BIF', label: 'Burundian Franc', symbol: 'FBu', flag: '🇧🇮' },
    { code: 'BMD', label: 'Bermudian Dollar', symbol: '$', flag: '🇧🇲' },
    { code: 'BND', label: 'Brunei Dollar', symbol: '$', flag: '🇧🇳' },
    { code: 'BOB', label: 'Bolivian Boliviano', symbol: 'Bs.', flag: '🇧🇴' },
    { code: 'BRL', label: 'Brazilian Real', symbol: 'R$', flag: '🇧🇷' },
    { code: 'BSD', label: 'Bahamian Dollar', symbol: '$', flag: '🇧🇸' },
    { code: 'BTN', label: 'Bhutanese Ngultrum', symbol: 'Nu.', flag: '🇧🇹' },
    { code: 'BWP', label: 'Botswanan Pula', symbol: 'P', flag: '🇧🇼' },
    { code: 'BYN', label: 'Belarusian Ruble', symbol: 'Br', flag: '🇧🇾' },
    { code: 'BZD', label: 'Belize Dollar', symbol: '$', flag: '🇧🇿' },
    { code: 'CAD', label: 'Canadian Dollar', symbol: '$', flag: '🇨🇦' },
    { code: 'CDF', label: 'Congolese Franc', symbol: 'FC', flag: '🇨🇩' },
    { code: 'CHF', label: 'Swiss Franc', symbol: 'CHF', flag: '🇨🇭' },
    { code: 'CLP', label: 'Chilean Peso', symbol: '$', flag: '🇨🇱' },
    { code: 'CNY', label: 'Chinese Yuan', symbol: '¥', flag: '🇨🇳' },
    { code: 'COP', label: 'Colombian Peso', symbol: '$', flag: '🇨🇴' },
    { code: 'CRC', label: 'Costa Rican Colón', symbol: '₡', flag: '🇨🇷' },
    { code: 'CUP', label: 'Cuban Peso', symbol: '$', flag: '🇨🇺' },
    { code: 'CVE', label: 'Cape Verdean Escudo', symbol: 'Esc', flag: '🇨🇻' },
    { code: 'CZK', label: 'Czech Koruna', symbol: 'Kč', flag: '🇨🇿' },
    { code: 'DJF', label: 'Djiboutian Franc', symbol: 'Fdj', flag: '🇩🇯' },
    { code: 'DKK', label: 'Danish Krone', symbol: 'kr', flag: '🇩🇰' },
    { code: 'DOP', label: 'Dominican Peso', symbol: '$', flag: '🇩🇴' },
    { code: 'DZD', label: 'Algerian Dinar', symbol: 'د.ج', flag: '🇩🇿' },
    { code: 'EGP', label: 'Egyptian Pound', symbol: '£', flag: '🇪🇬' },
    { code: 'ERN', label: 'Eritrean Nakfa', symbol: 'Nkf', flag: '🇪🇷' },
    { code: 'ETB', label: 'Ethiopian Birr', symbol: 'Br', flag: '🇪🇹' },
    { code: 'EUR', label: 'Euro', symbol: '€', flag: '🇪🇺' },
    { code: 'FJD', label: 'Fijian Dollar', symbol: '$', flag: '🇫🇯' },
    { code: 'FKP', label: 'Falkland Islands Pound', symbol: '£', flag: '🇫🇰' },
    { code: 'FOK', label: 'Faroese Króna', symbol: 'kr', flag: '🇫🇴' },
    { code: 'GBP', label: 'British Pound Sterling', symbol: '£', flag: '🇬🇧' },
    { code: 'GEL', label: 'Georgian Lari', symbol: '₾', flag: '🇬🇪' },
    { code: 'GGP', label: 'Guernsey Pound', symbol: '£', flag: '🇬🇬' },
    { code: 'GHS', label: 'Ghanaian Cedi', symbol: '₵', flag: '🇬🇭' },
    { code: 'GIP', label: 'Gibraltar Pound', symbol: '£', flag: '🇬🇮' },
    { code: 'GMD', label: 'Gambian Dalasi', symbol: 'D', flag: '🇬🇲' },
    { code: 'GNF', label: 'Guinean Franc', symbol: 'FG', flag: '🇬🇳' },
    { code: 'GTQ', label: 'Guatemalan Quetzal', symbol: 'Q', flag: '🇬🇹' },
    { code: 'GYD', label: 'Guyanese Dollar', symbol: '$', flag: '🇬🇾' },
    { code: 'HKD', label: 'Hong Kong Dollar', symbol: '$', flag: '🇭🇰' },
    { code: 'HNL', label: 'Honduran Lempira', symbol: 'L', flag: '🇭🇳' },
    { code: 'HRK', label: 'Croatian Kuna', symbol: 'kn', flag: '🇭🇷' },
    { code: 'HTG', label: 'Haitian Gourde', symbol: 'G', flag: '🇭🇹' },
    { code: 'HUF', label: 'Hungarian Forint', symbol: 'Ft', flag: '🇭🇺' },
    { code: 'IDR', label: 'Indonesian Rupiah', symbol: 'Rp', flag: '🇮🇩' },
    { code: 'ILS', label: 'Israeli Shekel', symbol: '₪', flag: '🇮🇱' },
    { code: 'IMP', label: 'Isle of Man Pound', symbol: '£', flag: '🇮🇲' },
    { code: 'INR', label: 'Indian Rupee', symbol: '₹', flag: '🇮🇳' },
    { code: 'IQD', label: 'Iraqi Dinar', symbol: 'ع.د', flag: '🇮🇶' },
    { code: 'IRR', label: 'Iranian Rial', symbol: '﷼', flag: '🇮🇷' },
    { code: 'ISK', label: 'Icelandic Króna', symbol: 'kr', flag: '🇮🇸' },
    { code: 'JEP', label: 'Jersey Pound', symbol: '£', flag: '🇯🇪' },
    { code: 'JMD', label: 'Jamaican Dollar', symbol: '$', flag: '🇯🇲' },
    { code: 'JOD', label: 'Jordanian Dinar', symbol: 'د.ا', flag: '🇯🇴' },
    { code: 'JPY', label: 'Japanese Yen', symbol: '¥', flag: '🇯🇵' },
    { code: 'KES', label: 'Kenyan Shilling', symbol: 'KSh', flag: '🇰🇪' },
    { code: 'KGS', label: 'Kyrgystani Som', symbol: 'с', flag: '🇰🇬' },
    { code: 'KHR', label: 'Cambodian Riel', symbol: '៛', flag: '🇰🇭' },
    { code: 'KID', label: 'Kiribati Dollar', symbol: '$', flag: '🇰🇮' },
    { code: 'KMF', label: 'Comorian Franc', symbol: 'CF', flag: '🇰🇲' },
    { code: 'KRW', label: 'South Korean Won', symbol: '₩', flag: '🇰🇷' },
    { code: 'KWD', label: 'Kuwaiti Dinar', symbol: 'د.ك', flag: '🇰🇼' },
    { code: 'KYD', label: 'Cayman Islands Dollar', symbol: '$', flag: '🇰🇾' },
    { code: 'KZT', label: 'Kazakhstani Tenge', symbol: '₸', flag: '🇰🇿' },
    { code: 'LAK', label: 'Laotian Kip', symbol: '₭', flag: '🇱🇦' },
    { code: 'LBP', label: 'Lebanese Pound', symbol: 'ل.ل', flag: '🇱🇧' },
    { code: 'LKR', label: 'Sri Lankan Rupee', symbol: 'Rs', flag: '🇱🇰' },
    { code: 'LRD', label: 'Liberian Dollar', symbol: '$', flag: '🇱🇷' },
    { code: 'LSL', label: 'Lesotho Loti', symbol: 'L', flag: '🇱🇸' },
    { code: 'LYD', label: 'Libyan Dinar', symbol: 'ل.د', flag: '🇱🇾' },
    { code: 'MAD', label: 'Moroccan Dirham', symbol: 'د.م.', flag: '🇲🇦' },
    { code: 'MDL', label: 'Moldovan Leu', symbol: 'L', flag: '🇲🇩' },
    { code: 'MGA', label: 'Malagasy Ariary', symbol: 'Ar', flag: '🇲🇬' },
    { code: 'MKD', label: 'Macedonian Denar', symbol: 'ден', flag: '🇲🇰' },
    { code: 'MMK', label: 'Myanmar Kyat', symbol: 'Ks', flag: '🇲🇲' },
    { code: 'MNT', label: 'Mongolian Tugrik', symbol: '₮', flag: '🇲🇳' },
    { code: 'MOP', label: 'Macanese Pataca', symbol: 'MOP$', flag: '🇲🇴' },
    { code: 'MRU', label: 'Mauritanian Ouguiya', symbol: 'UM', flag: '🇲🇷' },
    { code: 'MUR', label: 'Mauritian Rupee', symbol: '₨', flag: '🇲🇺' },
    { code: 'MVR', label: 'Maldivian Rufiyaa', symbol: 'Rf', flag: '🇲🇻' },
    { code: 'MWK', label: 'Malawian Kwacha', symbol: 'MK', flag: '🇲🇼' },
    { code: 'MXN', label: 'Mexican Peso', symbol: '$', flag: '🇲🇽' },
    { code: 'MYR', label: 'Malaysian Ringgit', symbol: 'RM', flag: '🇲🇾' },
    { code: 'MZN', label: 'Mozambican Metical', symbol: 'MT', flag: '🇲🇿' },
    { code: 'NAD', label: 'Namibian Dollar', symbol: '$', flag: '🇳🇦' },
    { code: 'NGN', label: 'Nigerian Naira', symbol: '₦', flag: '🇳🇬' },
    { code: 'NIO', label: 'Nicaraguan Córdoba', symbol: 'C$', flag: '🇳🇮' },
    { code: 'NOK', label: 'Norwegian Krone', symbol: 'kr', flag: '🇳🇴' },
    { code: 'NPR', label: 'Nepalese Rupee', symbol: '₨', flag: '🇳🇵' },
    { code: 'NZD', label: 'New Zealand Dollar', symbol: '$', flag: '🇳🇿' },
    { code: 'OMR', label: 'Omani Rial', symbol: 'ر.ع.', flag: '🇴🇲' },
    { code: 'PAB', label: 'Panamanian Balboa', symbol: 'B/.', flag: '🇵🇦' },
    { code: 'PEN', label: 'Peruvian Sol', symbol: 'S/', flag: '🇵🇪' },
    { code: 'PGK', label: 'Papua New Guinean Kina', symbol: 'K', flag: '🇵🇬' },
    { code: 'PHP', label: 'Philippine Peso', symbol: '₱', flag: '🇵🇭' },
    { code: 'PKR', label: 'Pakistani Rupee', symbol: '₨', flag: '🇵🇰' },
    { code: 'PLN', label: 'Polish Złoty', symbol: 'zł', flag: '🇵🇱' },
    { code: 'PYG', label: 'Paraguayan Guarani', symbol: '₲', flag: '🇵🇾' },
    { code: 'QAR', label: 'Qatari Rial', symbol: 'ر.ق', flag: '🇶🇦' },
    { code: 'RON', label: 'Romanian Leu', symbol: 'lei', flag: '🇷🇴' },
    { code: 'RSD', label: 'Serbian Dinar', symbol: 'дин', flag: '🇷🇸' },
    { code: 'RUB', label: 'Russian Ruble', symbol: '₽', flag: '🇷🇺' },
    { code: 'RWF', label: 'Rwandan Franc', symbol: 'FRw', flag: '🇷🇼' },
    { code: 'SAR', label: 'Saudi Riyal', symbol: 'ر.س', flag: '🇸🇦' },
    { code: 'SBD', label: 'Solomon Islands Dollar', symbol: '$', flag: '🇸🇧' },
    { code: 'SCR', label: 'Seychellois Rupee', symbol: '₨', flag: '🇸🇨' },
    { code: 'SDG', label: 'Sudanese Pound', symbol: '£', flag: '🇸🇩' },
    { code: 'SEK', label: 'Swedish Krona', symbol: 'kr', flag: '🇸🇪' },
    { code: 'SGD', label: 'Singapore Dollar', symbol: '$', flag: '🇸🇬' },
    { code: 'SHP', label: 'St Helena Pound', symbol: '£', flag: '🇸🇭' },
    { code: 'SLE', label: 'Sierra Leonean Leone', symbol: 'Le', flag: '🇸🇱' },
    { code: 'SLL', label: 'Sierra Leonean Leone (old)', symbol: 'Le', flag: '🇸🇱' },
    { code: 'SOS', label: 'Somali Shilling', symbol: 'Sh', flag: '🇸🇴' },
    { code: 'SRD', label: 'Surinamese Dollar', symbol: '$', flag: '🇸🇷' },
    { code: 'SSP', label: 'South Sudanese Pound', symbol: '£', flag: '🇸🇸' },
    { code: 'STN', label: 'São Tomé & Príncipe Dobra', symbol: 'Db', flag: '🇸🇹' },
    { code: 'SYP', label: 'Syrian Pound', symbol: '£', flag: '🇸🇾' },
    { code: 'SZL', label: 'Swazi Lilangeni', symbol: 'E', flag: '🇸🇿' },
    { code: 'THB', label: 'Thai Baht', symbol: '฿', flag: '🇹🇭' },
    { code: 'TJS', label: 'Tajikistani Somoni', symbol: 'SM', flag: '🇹🇯' },
    { code: 'TMT', label: 'Turkmenistani Manat', symbol: 'T', flag: '🇹🇲' },
    { code: 'TND', label: 'Tunisian Dinar', symbol: 'د.ت', flag: '🇹🇳' },
    { code: 'TOP', label: 'Tongan Paʻanga', symbol: 'T$', flag: '🇹🇴' },
    { code: 'TRY', label: 'Turkish Lira', symbol: '₺', flag: '🇹🇷' },
    { code: 'TTD', label: 'Trinidad & Tobago Dollar', symbol: '$', flag: '🇹🇹' },
    { code: 'TVD', label: 'Tuvaluan Dollar', symbol: '$', flag: '🇹🇻' },
    { code: 'TWD', label: 'New Taiwan Dollar', symbol: 'NT$', flag: '🇹🇼' },
    { code: 'TZS', label: 'Tanzanian Shilling', symbol: 'Sh', flag: '🇹🇿' },
    { code: 'UAH', label: 'Ukrainian Hryvnia', symbol: '₴', flag: '🇺🇦' },
    { code: 'UGX', label: 'Ugandan Shilling', symbol: 'Sh', flag: '🇺🇬' },
    { code: 'UYU', label: 'Uruguayan Peso', symbol: '$', flag: '🇺🇾' },
    { code: 'UZS', label: 'Uzbekistani Som', symbol: 'soʻm', flag: '🇺🇿' },
    { code: 'VES', label: 'Venezuelan Bolívar', symbol: 'Bs.', flag: '🇻🇪' },
    { code: 'VND', label: 'Vietnamese Đồng', symbol: '₫', flag: '🇻🇳' },
    { code: 'VUV', label: 'Vanuatu Vatu', symbol: 'Vt', flag: '🇻🇺' },
    { code: 'WST', label: 'Samoan Tala', symbol: 'T', flag: '🇼🇸' },
    { code: 'XAF', label: 'Central African CFA Franc', symbol: 'FCFA', flag: '🇨🇫' },
    { code: 'XCD', label: 'East Caribbean Dollar', symbol: '$', flag: '🇽🇨' },
    { code: 'XDR', label: 'IMF Special Drawing Rights', symbol: 'SDR', flag: '🌐' },
    { code: 'XOF', label: 'West African CFA Franc', symbol: 'CFA', flag: '🇨🇮' },
    { code: 'XPF', label: 'CFP Franc', symbol: '₣', flag: '🇵🇫' },
    { code: 'YER', label: 'Yemeni Rial', symbol: '﷼', flag: '🇾🇪' },
    { code: 'ZAR', label: 'South African Rand', symbol: 'R', flag: '🇿🇦' },
    { code: 'ZMW', label: 'Zambian Kwacha', symbol: 'ZK', flag: '🇿🇲' },
    { code: 'ZWL', label: 'Zimbabwean Dollar', symbol: '$', flag: '🇿🇼' },
];

export default CurrenciesCode;